### ISSUE TITLE
No config chosen

### ISSUE THREAD

**Issue by jp1017** [jp1017/Android-Collection#12]
**Comment:**
```
java.lang.IllegalArgumentException: No config chosen
	at android.opengl.GLSurfaceView$BaseConfigChooser.chooseConfig(GLSurfaceView.java:874)
	at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1024)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1401)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)


```

**Number:** 	 1

**URL:** 	 https://instabug.com/applications/inst-79c34325-8d04-4014-a072-34e45623b08c/issues/1

**Type:** 	 crash

**Status:** 	 New

**Email:** 	 

**Reported At:** 	 2016-04-01 02:03:03 UTC

**Location:** 	 Shandong Sheng, China

**Device:** 	 unknown Android SDK built for x86 / SDK Level 19

**Memory:** 	 125.0/0.0 MB

**Storage:** 	 0.0/98.0 GB

**Connectivity:** 	 Carrier: Android, WiFi: Not Connected

**Battery:** 	 50, Charging through AC Charger

**App Version:** 	 1.1.1 (1)

**Duration:** 	 00:00:07

**User Data:** 	 

**Console Log:**
```
 Exception: java.lang.IllegalArgumentException
03-31 22:03:03.839 E/INSTABUG - Instabug( 1954): java.lang.IllegalArgumentException: No config chosen
03-31 22:03:03.839 E/INSTABUG - Instabug( 1954): 	at android.opengl.GLSurfaceView$BaseConfigChooser.chooseConfig(GLSurfaceView.java:874)
03-31 22:03:03.839 E/INSTABUG - Instabug( 1954): 	at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1024)
03-31 22:03:03.839 E/INSTABUG - Instabug( 1954): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1401)
03-31 22:03:03.839 E/INSTABUG - Instabug( 1954): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
03-31 22:03:03.869 W/DeviceId( 1954): galaxy lib host missing meta-data,make sure you know the right way to integrate galaxy
03-31 22:03:03.869 W/DeviceId( 1954): galaxy lib host missing meta-data,make sure you know the right way to integrate galaxy
03-31 22:03:03.869 W/DeviceId( 1954): galaxy lib host missing meta-data,make sure you know the right way to integrate galaxy
03-31 22:03:03.889 D/dalvikvm( 2124): Not late-enabling CheckJNI (already on)
03-31 22:03:03.999 D/AndroidHeapDumper( 2124): Could not attempt cleanup, external storage not mounted.
03-31 22:03:03.999 D/dalvikvm( 2124): Trying to load lib /data/app-lib/com.inst.instdriver-1/libBaiduMapSDK_base_v3_7_1.so 0xb2f6a538
03-31 22:03:03.999 D/dalvikvm( 2124): Added shared lib /data/app-lib/com.inst.instdriver-1/libBaiduMapSDK_base_v3_7_1.so 0xb2f6a538
03-31 22:03:04.029 D/auth info( 2124): mcode: 53:FD:54:DC:19:0F:2D:AC:B5:73:9E:F1:1A:68:88:1B:8B:E8:54:42;com.inst.instdriver
03-31 22:03:04.039 I/INSTABUG - Builder( 2124): Initializing Instabug v2.3.1
03-31 22:03:04.049 D/dalvikvm( 2124): GC_FOR_ALLOC freed 335K, 13 free 2819K/3216K, paused 3ms, total 5ms
03-31 22:03:04.069 D/baidu_location_service( 2124): baidu location service start1 ...2124
03-31 22:03:04.089 W/DeviceId( 2124): galaxy lib host missing meta-data,make sure you know the right way to integrate galaxy
03-31 22:03:04.089 W/DeviceId( 2124): galaxy lib host missing meta-data,make sure you know the right way to integrate galaxy
03-31 22:03:04.089 W/DeviceId( 2124): galaxy lib host missing meta-data,make sure you know the right way to integrate galaxy
03-31 22:03:04.379 D/dalvikvm( 2124): GC_FOR_ALLOC freed 361K, 13 free 2953K/3376K, paused 3ms, total 4ms
03-31 22:03:04.549 W/logger-jpjp( 1954): ╔════════════════════════════════════════════════════════════════════════════════════════
03-31 22:03:04.549 W/logger-jpjp( 1954): ║ GeoCoder$a.j  (null:-1)
03-31 22:03:04.619 W/logger-jpjp( 1954): ╟────────────────────────────────────────────────────────────────────────────────────────
03-31 22:03:04.619 W/logger-jpjp( 1954): ║ address: 
03-31 22:03:04.619 W/logger-jpjp( 1954): ╚════════════════════════════════════════════════════════════════════════════════════════
03-31 22:03:04.619 I/Choreographer( 1954): Skipped 41 frames!  The application may be doing too much work on its main thread.

```

**Instabug Log:**
```

```

**User Steps:**
```
03-31 22:03:59     com.inst.instdriver.ui.activity.MainActivity was resumed.
03-31 22:03:00     com.inst.instdriver.ui.activity.MainActivity was paused 
03-31 22:03:00     com.inst.instdriver.ui.activity.LoginActivity was resumed.
03-31 22:03:02     com.inst.instdriver.ui.activity.LoginActivity was paused 
03-31 22:03:03     com.inst.instdriver.ui.activity.MainActivity was resumed.
```

**Current View:** 	 com.inst.instdriver.ui.activity.MainActivity

**Comment by jp1017** [comment]
![43468-028c429ef0d15498](https://cloud.githubusercontent.com/assets/7868514/15390811/7269dbac-1df0-11e6-92a7-899ef62bbbb4.png)
